### ISSUE TITLE
Links opening in wrong browser

### ISSUE THREAD

**Issue by volt4ire** [johnste/finicky#34]
I have my Finicky configuration set to open most links in Firefox, with the exception of Youtube links which are set to open in to an app called Fenêtre, and Spotify ones going to Spotify. However, whenever I open a link it opens in Chrome. I have included my .finicky.js configuration file below. Can you please help me get the links to open in Firefox or the other two apps? Thanks!

finicky.setDefaultBrowser('org.mozilla.firefox')

// Open Spotify links in client
finicky.onUrl(function(url, opts) {
    if (url.match(/^https?:\/\/open\.spotify\.com/)) {
        return {
            bundleIdentifier: 'com.spotify.client'
        }
    }
});

// Open Youtube links in client
finicky.onUrl(function(url, opts) {
    if (url.match((/^https?:\/\/twitter\.com) {
        return {
            bundleIdentifier: 'com.yoannmoinet.fenetre'
        }
    }
});

**Comment by johnste** [comment]
Hey Robert, sorry for not getting back to you sooner.

Looks like there are a few syntax errors in your code. I fixed them and ran the code through prettier. I also escaped a few slashes in your regular expressions. Please try this and see if it works:

```javascript
finicky.setDefaultBrowser("org.mozilla.firefox");

// Open Spotify links in client
finicky.onUrl(function(url, opts) {
  if (url.match(/^https?:\/\/open.spotify.com/)) {
    return {
      bundleIdentifier: "com.spotify.client"
    };
  }
});

// Open Youtube links in client
finicky.onUrl(function(url, opts) {
  if (url.match(/^https?:\/\/twitter.com/)) {
    return {
      bundleIdentifier: "com.yoannmoinet.fenetre"
    };
  }
});
```

**Comment by volt4ire** [comment]
Thanks! This fixes it for Spotify but it's still not working in Youtube – it opens those links in Firefox rather than whichever app I set for Youtube links.

**Comment by johnste** [comment]
Your youtube rule checks for the twitter domain, could that be it?

**Comment by volt4ire** [comment]
Thanks I noticed that problem earlier and changed it, but the youtube links still aren't opening in the browser I want (which is Chrome for now). My .finicky.js file is now as follows: 

finicky.setDefaultBrowser("org.mozilla.firefox");

// Open Spotify links in client
finicky.onUrl(function(url, opts) {
  if (url.match(/^https?:\/\/open.spotify.com/)) {
    return {
      bundleIdentifier: "com.spotify.client"
    };
  }
});

// Open Youtube links in client
finicky.onUrl(function(url, opts) {
  if (url.match(/^https?:\/\/youtube.com/)) {
    return {
      bundleIdentifier: "com.google.Chrome"
    };
  }
});

**Comment by johnste** [comment]
It's hard for me to confirm, but maybe you need a regex that also matches the `www` subdomain
like so: `/^https?:\/\/(www.)?youtube.com/`

I've confirmed that it works for me. 

Also you need to make sure you escape any `/` characters in your regexes since finicky won't report any parsing or syntax errors. 

If it still won't work, you can use `finicky.log('logging');` to debug the execution of your config.

**Comment by volt4ire** [comment]
Your solution for the www subdomain (/^https?:\/\/(www.)?youtube.com/) worked – thanks so much for your help!!
